apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie

  template:
    metadata:
      labels:
        app: mealie

    spec:
 #     securityContext:
 #       fsGroup: 1000
 #       runAsUser: 1000
 #       runAsGroup: 1000

      containers:
        - name: mealie
          image:  ghcr.io/mealie-recipes/mealie:v3.1.2

          envFrom:
            - configMapRef:
                name: mealie-configmap

          ports:
            - containerPort: 9000
              protocol: TCP

          volumeMounts:
            - mountPath: /app/metadata
          name: mealie-data

      restartPolicy: Always

      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
