apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:0MIJ2F2KQjps9M1ijRaONAsmR8UGO/9mR//gPbL/Di46BHkFGclCDpazk1hjzqJNKYN836gzAacswHxavWPfjFcf9GWsf38AQXHRZB71G7RhaWgbmJXSRbIgIFMqwxWoGf4I5H9UOCdIKHkZlPHWcK/Uv+nvXGBQdfWoDXS2/Q9ShOQ5ePeih33Z9JsVdMXzU+neEZqLr49MeJFfjXfW6zzmoHST5oOrOJDTh4nu3A+HXX0Z2FQDmeVopM8loxw53hfGCP7p1a8gkzd65oIHXiPaymGYZh1FtWDtPDee+HbvvOw2WkgJvX4sxiA=,iv:qqkDVl0W/M0RrQEgF7shvenEudqSZytienFIbPdkiPQ=,tag:G2cfNXCMhH4vP7LDcukYXA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age16yfug5lv775x0678ulnx823uu6nh2qvnq8kfuy65tg8k2n6ulvjsqt6js7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK0haNm9XWFVDWFNZc2pN
            Y0xiVlR0TnBuYTMwRmgxYW5tK0I3d2VYalFzCk9aRDY1akVveWlETWwzTFgwdVJ6
            OXkxQ3YrWFlaK0lpUnpHMmRWMmd0dlEKLS0tIHA0d0R4cElFSVFaOTJJenYxb0JS
            clpqa0hrZ215SzZhZVFzOGNPaVBvUkUKb2hYHv/eqiLrApa5bmC1rNScGWhRNNRz
            4WCBlGLQ6jVz4hcA31fVoLYYlvodL3jSpMnCGfehFWvugUWnla/hvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T00:07:24Z"
    mac: ENC[AES256_GCM,data:K2thaNi8MCdskamclMKfOMZshdiFprfnjVu3Fs4NP/Zz+/hnwxrofzCFyf8UYAfmBEw+f8a9HM5meebdfWBJh56m3S2/LGTfbT+ZYJ5XlGhRhrE1lSKMQS9601RWZ8o0twZk543IUSAuazmWzLV9u3QiR4yKPAzjirs2kYNYyls=,iv:W7NokVN6Brj7Sf5w/NdkT3qIT0T3aIz34cHBKXy3oKY=,tag:vSpHBZufVN0QfSmfIVyzmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
